modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/refinedmods/refinedstorage-emi-integration"
license = "MIT"
[[mods]]
modId = "refinedstorage_emi_integration"
version = "${version}"
displayName = "Refined Storage - EMI Integration"
displayURL = "https://refinedmods.com/refined-storage"
authors = "Refined Mods"
description = '''
EMI integration for Refined Storage.
'''
[[dependencies.refinedstorage_emi_integration]]
modId = "refinedstorage"
type = "required"
versionRange = "2.0.0-milestone.4.7"
side = "BOTH"
[[dependencies.refinedstorage_emi_integration]]
modId = "emi"
type = "required"
versionRange = "[1.1.7,)"
side = "BOTH"
